### ISSUE TITLE
Backslash \ in song ignored before vertical |

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#200]
Another fairly niche case(!), but a `\` seems to get lost when immediately before `|`, in song source.
[backslash+vertical.cho.txt](https://github.com/ChordPro/chordpro/files/7839578/backslash%2Bvertical.cho.txt)
[backslash+vertical (guitar) git.pdf](https://github.com/ChordPro/chordpro/files/7839579/backslash%2Bvertical.guitar.git.pdf)
[backslash+vertical (noconfig).pdf](https://github.com/ChordPro/chordpro/files/7839580/backslash%2Bvertical.noconfig.pdf)

I use `\` and `/` to denote down- and up-strums, and `|` for bar or down-beat (as useful symbols within most character sets), combined with inline chords. Mostly works well, except with `\|`. I'm guessing the `\` gets treated somehow as an escape character.

Not sure if this classes as an issue, or just a constraint I need to work around. Present with both release v5.985 and git _083

**Comment by sciurius** [comment]
It is a bug in a library module that ChordPro uses.

See https://github.com/sciurius/perl-String-Interpolate-Named/issues/6 .

**Comment by sciurius** [comment]
Upgrading perl modeule `String::Interpolate::Named` to 1.02 should solve this.

**Comment by gwyndaf** [comment]
Yes, that seems to have fixed it.

**Comment by gwyndaf** [comment]
A consequence of this seems it's no longer necessary to double-escape most `|` (and possibly other special characters) in conditional metadata substitutions, as described in [documentation](https://www.chordpro.org/beta/chordpro-configuration-format-strings/), so maybe needs documentation update?

Interestingly, nested substitutions do still appear to need double-escape as `\\|` but results unpredictable. I'm sure this is an extremely minor case and probably amply-covered by the 'bug or feature' comment :)
[title_string_test.cho.txt](https://github.com/ChordPro/chordpro/files/7855915/title_string_test.cho.txt)
[title_string_test.cho.pdf](https://github.com/ChordPro/chordpro/files/7855916/title_string_test.cho.pdf)

Same behaviour on both release v5.985 and git 083.

**Comment by gwyndaf** [comment]
Apologies: that seems to apply only for metadata substitutions in _song body_. Seems like metadata in config file might still need double-escaping.

Attached minimal config still processes ok, but gives odd results as in PDF title line.
[title-config.json.txt](https://github.com/ChordPro/chordpro/files/7856119/title-config.json.txt)
[title-config-test.pdf](https://github.com/ChordPro/chordpro/files/7856120/title-config-test.pdf)
Prior to `String::Interpolate::Named` update, top left of page was displaying `key_actual` value (or `key` if missing).

Doesn't actually affect my usage as I'd only used the conditional substitutions for `key` when `key_actual` value was missing, but now that seems present in all cases, so I can work around, and this is largely a FYI.

**Comment by sciurius** [comment]
That's not how it is supposed to behave. I'll investigate.

**Comment by sciurius** [comment]
Fixed in String::Interpolate::Named 1.03.

Explanation: Substitution works from inside out. For example,
````
%{key|%{time|%{}}}
````
First, `%{time|%{}}` is handled. Assume this yields `4/4`. Then in the 2nd pass `%{key|4/4}' is processed.
Now let's try to substitute a vertical bar when `time` has a value.

`%{time||}` will (obviously) not work.
`%{time|\|}` will yield a single `|`
When we nest this like `%{key|%{time|\|}}` then the 2nd pass sees `%{key||}` which is not what we want. To get a `\|` in the 2nd pass, we need an escaped bar **preceded with** an escaped backslash. So it becomes
````
%{key|%{time|\\\|}}
````
In a string the backslashes must be escaped once more, so your title specification in the config becomes:
````
      "title"     : [ "%{key_actual|%{}  \\|  |%{key|%{}  \\\\\\|  }}%{time|%{}  \\|  }%{tempo|~%{}bpm  \\|  }%{capo|capo %{}}", "", "%{title}" ]
````

I love what you're doing ☺.

**Comment by gwyndaf** [comment]
I can't claim credit for methodical testing: I'm simply putting some songs together, and pushing the limits of design and layout capabilities, then get curious when the unexpected happens!

Thanks for the clear explanation. Now seems to work as expected in both song and config contexts.
