### ISSUE TITLE
Missing standard and page related metadata

### ISSUE THREAD

**Issue by devnibo** [ChordPro/chordpro#531]
## Describe the bug
The values of the following list of metadata item names aren't shown in the generated PDF file when including them with `%{<name>}`:
- chords
- chordpro
- chordpro.songsource
- chordpro.version
- numchords
- songindex
- user.fullname
- page
- page.side
- page.class
- pages

### To Reproduce
1. Save this test song as a file `substitution.cho`
```
{title: The Title}

[E]This [A]is [B]the song.

{comment: Standard metadata}

chords: %{chords}
chordpro: %{chordpro}
chordpro.songsource: %{chordpro.songsource}
chordpro.version: %{chordpro.version}
instrument: %{instrument}
instrument.type: %{instrument.type}
instrument.description: %{instrument.description}
numchords: %{numchords}
songindex: %{songindex}
today: %{today}
tuning: %{tuning}
user: %{user}
user.name: %{user.name}
user.fullname: %{user.fullname}

{comment: Page related metadata}

page: %{page}
page.side: %{page.side}
page.class: %{page.class}
pages: %{pages}

```
3. Run `chordpro substitution.cho`
4. Open the generated PDF file

### Expected behavior

I expected the metadata items to show their value based on https://www.chordpro.org/beta/chordpro-configuration-format-strings/#standard-metadata and https://www.chordpro.org/beta/chordpro-configuration-format-strings/#page-related-metadata

### Attachments

```
[~] chordpro --debug test/substitution.cho
This is ChordPro core 6.050 
ChordPro invoked: --debug test/substitution.cho
Writing output to test/substitution.pdf
Reading: <builtin>
Reading: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Verify config "/usr/share/perl5/site_perl/ChordPro/res/config/guitar.json"
Config[0]: <builtin>
Config[1]: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Process: <builtin>
Process: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Chords: Created parser for common
Chords: Created parser for common
Processed 418 chord entries
Totals: 672 config chords
Parsers:
  common (active)
Processing song test/substitution.cho...
Parsers at start of test/substitution.cho: *common
Processed song...
Generating PDF test/substitution.pdf...
Reading: <builtin>
Reading: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Verify config "/usr/share/perl5/site_perl/ChordPro/res/config/guitar.json"
Config[0]: <builtin>
Config[1]: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Process: <builtin>
Process: /usr/share/perl5/site_perl/ChordPro/res/config/guitar.json
Chords: Created parser for common
Processed 418 chord entries
Totals: 672 config chords
Generated PDF...
[~]
```

[substitution.pdf](https://github.com/user-attachments/files/18904762/substitution.pdf)

## System information
 - OS: Arch Linux
 - Where did you get ChordPro from? CPAN

 - ChordPro version: 6.050
 - Perl version: 5.40.1

**Comment by sciurius** [comment]
Finally someone really testing these ☺.

The [page related items](https://www.chordpro.org/beta/chordpro-configuration-format-strings/#page-related-metadata) are available to page headings/footers only.

The same is true for `songindex`, `chords` and `numchords`. I shall fix this in the documentation.

I've fixed `chordpro.songsource` to be available to the song content.

Please upgrade to the newest version before reporting percieved bugs.

To test, run `6.070_063` from git.

**Comment by devnibo** [comment]
Is `6.070_063` the name of a git branch or a git tag? I can't find one or the other with that name.

**Comment by sciurius** [comment]
It is the latest version of the `dev` branch.

**Comment by devnibo** [comment]
I checked out the latest commit on the `dev` branch which was/is https://github.com/ChordPro/chordpro/commit/0e93e66dad8a3c4a40905b4e3920823a7e5a2fe4. I tested again and the metadata item `chordpro.songsource` shows the input file path as expected. `user.fullname` still doesn't show anything.

**Comment by sciurius** [comment]
Did you set a user fullname in the config?

If missing, it defaults to the GCOS field in the passwd data. What is the output of
````
getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1
````

**Comment by devnibo** [comment]
> Did you set a user fullname in the config?

No.

The following output shows that I don't have fullname set.

```
[~] getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1v

[~] getent passwd $USER
robin:x:1000:1000::/home/robin:/bin/bash
[~] 
```

I didn't know you could set a full name under Linux. After setting it with `sudo chfn -f '<fullname>' $USER` I can see that information when I use the metadata substitution `%{user.fullname}`. Thanks for pointing me to that topic.
